import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, FlaskConical, ShieldAlert } from "lucide-react";
import { evaluateJourney, unavailableLabState, type LabStatus } from "@/lib/invariantLab";
import { emptyEcosystemLoad, loadEcosystemFeed } from "@/lib/ecosystem";
import { incrementLocalCount, LAB_PREDICTION_KEY, readLocalCount } from "@/lib/localMetrics";

export default function InvariantLab() {
  const [feed, setFeed] = useState(emptyEcosystemLoad); const [journeyId, setJourneyId] = useState(""); const [mode, setMode] = useState<"baseline" | "mutation">("baseline"); const [prediction, setPrediction] = useState<LabStatus | null>(null); const [record, setRecord] = useState(() => ({ attempts: readLocalCount(LAB_PREDICTION_KEY), correct: 0 }));
  useEffect(() => { void loadEcosystemFeed().then((next) => { setFeed(next); if (next.feed) setJourneyId(next.feed.journeys[0].id); }); }, []);
  const journey = feed.feed?.journeys.find((item) => item.id === journeyId) ?? feed.feed?.journeys[0];
  const state = useMemo(() => journey ? evaluateJourney(journey, mode) : unavailableLabState(feed.message ?? "Loading fixture-backed release feed…"), [journey, mode, feed.message]);
  const isBaseline = state.mode === "baseline"; const canMutate = prediction !== null && !!journey;
  const applyMutation = () => { if (!canMutate || !journey) return; const nextMode = isBaseline ? "mutation" : "baseline"; const nextState = evaluateJourney(journey, nextMode); const correct = prediction === nextState.receipt.status; setRecord((value) => ({ attempts: incrementLocalCount(LAB_PREDICTION_KEY), correct: value.correct + (correct ? 1 : 0) })); setMode(nextMode); setPrediction(null); };
  const selectJourney = (id: string) => { setJourneyId(id); setMode("baseline"); setPrediction(null); };
  return <section className="invariant-lab" aria-labelledby="lab-title"><div className="lab-intro"><p className="eyebrow">GUIDED INVARIANT LAB / FIXTURE-BACKED</p><h2 id="lab-title">Predict first. Then read the generated receipt.</h2><p>Every option below is loaded from the offline release feed generated from the shared six-adapter fixtures. The Lab is intentionally bounded; it does not infer beyond the declared predicate.</p><div className="lab-scope"><FlaskConical size={15} /> <span>{state.receipt.scope}</span></div></div><div className="lab-workbench"><div className="lab-control"><span className="eyebrow">CONTROLLED INPUT</span><h3>{journey?.title ?? "Release data"}</h3>{feed.feed && <label className="lab-selector">Choose predicate<select value={journey?.id ?? ""} onChange={(event) => selectJourney(event.target.value)}>{feed.feed.journeys.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}<pre className="lab-json" aria-label="Declared fixture input">{state.receipt.value}</pre><p>{state.label}</p>{isBaseline && journey && <fieldset className="lab-prediction"><legend>Before applying the declared mutation, what do you predict?</legend><label><input type="radio" name="prediction" checked={prediction === "verified"} onChange={() => setPrediction("verified")} /> The check stays verified</label><label><input type="radio" name="prediction" checked={prediction === "fail"} onChange={() => setPrediction("fail")} /> The check fails</label><label><input type="radio" name="prediction" checked={prediction === "unverifiable"} onChange={() => setPrediction("unverifiable")} /> The check becomes unverifiable</label></fieldset>}{!isBaseline && <p className="prediction-feedback">Your prediction was recorded locally. Restore the baseline to try another fixture.</p>}<button type="button" className="lab-mutation" disabled={!isBaseline || !canMutate} onClick={applyMutation}>{isBaseline ? "Apply fixture mutation" : "Restore baseline"}<ArrowRight size={14} /></button>{isBaseline && journey && !canMutate && <small className="lab-hint">Choose a prediction to unlock the mutation.</small>}<small className="lab-local">Local comprehension attempts on this browser: {record.attempts} · correct this session: {record.correct}</small></div><div className={`lab-receipt ${state.receipt.status}`}><div className="receipt-head"><span className="eyebrow">GENERATED RECEIPT</span><span className={`receipt-status ${state.receipt.status}`}>{state.receipt.status === "verified" ? <CheckCircle2 size={14} /> : <ShieldAlert size={14} />} {state.receipt.status}</span></div><h3>{state.receipt.predicate}</h3><div className="receipt-value">{state.receipt.status}</div><p>{state.receipt.explanation}</p><dl><div><dt>RECEIPT ID</dt><dd>{state.receipt.id}</dd></div><div><dt>SCOPE</dt><dd>{state.receipt.scope}</dd></div></dl></div></div></section>;
}
