import { describe, expect, it } from "vitest";
import { CorpusValidationError, validateLivingWordUpload } from "./livingWordValidation";

function word(index: number) { return { word_uri: `sov://text/hebrew/oshb/genesis/1/1/w${index}`, surface: "אב", chapter: 1, verse: 1, word_index: index, letters: [{ letter_uri: `sov://text/hebrew/oshb/genesis/1/1/w${index}/l1`, char: "א" }, { letter_uri: `sov://text/hebrew/oshb/genesis/1/1/w${index}/l2`, char: "ב" }] }; }
function validPayload() { return Buffer.from(JSON.stringify(Array.from({ length: 8086 }, (_, index) => word(index + 1)))); }
function expectCode(mutator: (payload: ReturnType<typeof validPayload>) => void, code: string) { const payload = validPayload(); mutator(payload); expect(() => validateLivingWordUpload("genesis_oshb", "Genesis_OSHB.json", payload)).toThrowError(expect.objectContaining({ code })); }

describe("governed Living Word source validation", () => {
  it("accepts a declared role/file pair only when the full source structure holds", () => expect(validateLivingWordUpload("genesis_oshb", "Genesis_OSHB.json", validPayload())).toMatchObject({ sourceRole: "genesis_oshb", wordCount: 8086, validator: "living-word-source.v1" }));
  it("rejects unrecognized roles and mismatched role/filename pairs", () => { expect(() => validateLivingWordUpload("other", "Genesis_OSHB.json", validPayload())).toThrowError(CorpusValidationError); expect(() => validateLivingWordUpload("genesis_oshb", "John_SBLGNT.json", validPayload())).toThrowError(expect.objectContaining({ code: "E_CORPUS_ROLE_FILENAME_MISMATCH" })); });
  it("rejects malformed JSON, non-array roots, and word floors below the declared minimum", () => { expect(() => validateLivingWordUpload("genesis_oshb", "Genesis_OSHB.json", Buffer.from("not-json"))).toThrowError(expect.objectContaining({ code: "E_CORPUS_JSON_INVALID" })); expect(() => validateLivingWordUpload("genesis_oshb", "Genesis_OSHB.json", Buffer.from("{}"))).toThrowError(expect.objectContaining({ code: "E_CORPUS_TOP_LEVEL_INVALID" })); expect(() => validateLivingWordUpload("genesis_oshb", "Genesis_OSHB.json", Buffer.from("[]"))).toThrowError(expect.objectContaining({ code: "E_CORPUS_WORD_COUNT" })); });
  it("rejects malformed word metadata, coordinates, and URI-field disagreement", () => { expectCode((payload) => { const data = JSON.parse(payload.toString()); delete data[0].surface; payload.set(Buffer.from(JSON.stringify(data))); }, "E_CORPUS_WORD_SCHEMA"); expectCode((payload) => { const data = JSON.parse(payload.toString()); data[0].chapter = 0; payload.set(Buffer.from(JSON.stringify(data))); }, "E_CORPUS_COORDINATE_INVALID"); expectCode((payload) => { const data = JSON.parse(payload.toString()); data[0].chapter = 2; payload.set(Buffer.from(JSON.stringify(data))); }, "E_CORPUS_URI_COORDINATE_MISMATCH"); });
  it("rejects malformed letter fields and surface-letter count divergence", () => { expectCode((payload) => { const data = JSON.parse(payload.toString()); data[0].letters[0].letter_uri = "bad"; payload.set(Buffer.from(JSON.stringify(data))); }, "E_CORPUS_LETTER_URI_INVALID"); expectCode((payload) => { const data = JSON.parse(payload.toString()); data[0].letters = []; payload.set(Buffer.from(JSON.stringify(data))); }, "E_CORPUS_LETTERS_INVALID"); expectCode((payload) => { const data = JSON.parse(payload.toString()); data[0].letters = data[0].letters.slice(0, 1); payload.set(Buffer.from(JSON.stringify(data))); }, "E_CORPUS_SURFACE_LETTER_MISMATCH"); });
});
